//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHasPermission
    {
        public int employee_id { get; set; }
        public string permission_name { get; set; }
        public Nullable<byte> priority { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
