//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousekeepingTicketList
    {
        public int ticket_number { get; set; }
        public string ticket_type { get; set; }
        public int opened_by { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public Nullable<int> closed_by { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime date_opened { get; set; }
        public Nullable<System.DateTime> date_closed { get; set; }
        public string priority { get; set; }
        public bool completed { get; set; }
        public string room_number { get; set; }
        public int Expr1 { get; set; }
    }
}
