//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int token_id { get; set; }
        public string token1 { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
